### ISSUE TITLE
README.md is misleading

### ISSUE THREAD

**Issue by tornac1234** [GrafDimenzio/ItemSpawner#1]
In the README.md, there's a config example that we should be able to use with the MoreWeapons plugins but the item IDs provided in this config are not related to the MoreWeapons IDs. In the config provided, it goes from 36 to 42 while in MoreWeapons, IDs are from 50 to 56. (It's not a big issue but if we try using the config we'll get some anoying error everytime a round starts)

**Comment by GrafDimenzio** [comment]
The Id's of MoreWeapons was changed when the Halloween Update was relased and I forgot to update them here.
However I fixed it now.
